### ISSUE TITLE
Feature Request or Quick Help: Live refresh of the prompt

### ISSUE THREAD

**Issue by maxlandon** [lmorg/readline#1]
Hello,

First of all thanks a lot for this library, which appears to be very useful, mainly thanks to its very nice completion/syntax system and Vim integration. Really loving it, can do so many things with this.
In the frame of a security project ([Wiregost](https://github.com/maxlandon/wiregost)), I'm using this package. However it misses a few things that I would love to see implemented, even by myself (in which case a little help, clues on where to search for/modify would be unvaluable).

These things are:
- Live refresh of the prompt line, like in the [readline package](https://github.com/chzyer/readline). This allows, for instance, to add things like `[I]` or `[N]` or `[V]` to notify Vim mode. This, by the way, would free up the clue line, which becomes briefly cluttered when entering Vim Normal mode.
- This is a bonus wish: You managed to provide a one-liner clue + completion in various forms. I use ZSH as a system shell, and far from wishing something as sophisticated (and probably useless), do you think it is possible "to stack up" these comp+clues like what ZSH provides (see picture) ?
![zsh_comp](https://user-images.githubusercontent.com/25826036/88076428-59b98300-cb7a-11ea-9e03-81560d5b4e7e.png)

I'm already grateful for even the tiniest help you may bring !

**Comment by maxlandon** [comment]
Hello again !
I have implemented all of my requests above: you should take a look ! => [maxlandon/readline](https://github.com/maxlandon/readline). 
Just go in the examples directory, I have modified your own example to feed my new completion system and Vim status.
Hope to hear from you, and thanks again for your wonderful library, that I have not yet finished to learn using !

**Comment by lmorg** [comment]
@maxlandon Hi sorry I hadn't responded sooner. The pandemic has sadly pulled me away from dev projects so completely missed this issue being raised.

Anyhow, the live refresh idea was built into the hint text (displayed below the prompt). Which admittedly doesn't have any documentation explaining (sorry about that!) but you can see it in action in https://asciinema.org/a/232714 (it's the blue text). That all said, I will have a read through your changes because they sound pretty neat.

**Comment by maxlandon** [comment]
Hello Laurence, 
My turn to apologize for answering that late !
However, I've worked a lot on the readline library, which I used for a security tool.
You can find my fork at https://github.com/maxlandon/readline. 

A few things beside:
- I've written the corresponding documentation
- My code is full of comments, it is almost as if I had written it for you.
- In the Wiki Home page, you will find a list of the files, with descriptions: this list is incomplete for a reason: these are the files I touched, added or modified.
- I've seen that your version of readline used in murex is a bit updated as compared to mine.
- I've fixed a few bugs (mainly related to cursor movement) that you might need.
- I would love to find a common playground on which we may enhance both libs, if you see any point in that. I'm all yours anyway!
- **I assume** that integrating the completion changes will not be very hard if you are interested by this in murex.

Another very important thing: I have received some grateful thanks for my library, and it would not have been possible without yours: I'm handing you those thanks, with mine added !
Finally don't hesitate to reach back for questions or suggestions !

**Comment by lmorg** [comment]
@maxlandon Thank you for the kind words. Really impressed with the documentation you've written.

Agreed that in an ideal world it would be good to share a common library. I'm about to dump the latest changes from murex back into this repository. There's a lot of bug fixes, some tests (finally) written but biggest change is support for wrapped lines -- where the line is longer than the term width. That was a major annoyance of my library and fixing that caused a fair amount of the rendering code (for want a better description) to be rewritten. So I suspect our code bases might have already diverged too much for the changes between each fork to be easily ported. That said, I'll definitely be diff'ing between the commits to what's doable.

Watch this space :D

**Comment by maxlandon** [comment]
Ohhh tooo bad I spent a whole week to support multiple lines ! My readine does it also as of now !
Ok I will take a look at this, I'll try to make some PRs to your fork as well !

**Comment by maxlandon** [comment]
Actually Laurence would you be kind enough to mail me at maximelandon gmail com ? I would like to discuss this, I've browsed your codebase: indeed many changes, our code differs a lot, but I am both willing to solve this AND to do it in a way that will not waste your time ! (I don't have a work right now so I tend to respect the schedule of those who have one !)
Thanks a lot for reaching back !

**Comment by lmorg** [comment]
email sent :)
